# Generated by Django 5.0 on 2025-08-04 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="images/icons_chat/default.png",
                upload_to="images/icons_chat/%Y/%m/%d",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                verbose_name="Иконка чата",
            ),
        ),
    ]
