# Generated by Django 5.0 on 2025-08-05 12:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_group_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateChat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="images/icons_chat/default.png",
                        upload_to="images/icons_chat/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))
                        ],
                        verbose_name="Иконка чата",
                    ),
                ),
                ("participants", models.ManyToManyField(limit_choices_to=2, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="private_chat",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.privatechat"
            ),
        ),
    ]
