# Generated by Django 5.0 on 2025-08-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_privatechat_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.group"
            ),
        ),
    ]
