# Generated by Django 5.0 on 2025-08-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_message_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privatechat",
            name="icon",
        ),
    ]
