# Generated by Django 5.0 on 2025-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_privatechat_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="count_message",
            field=models.BigIntegerField(default=0, verbose_name="Счетчик сообщений в день"),
        ),
    ]
