# Generated by Django 5.0 on 2025-07-30 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_is_active_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+79999999999' or '89999999999'.",
                        regex="^((\\+7)|8)\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "This username is already taken."},
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username may only contain lowercase English letters and underscores",
                        regex="^[a-z_]+$",
                    )
                ],
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True, verbose_name="URL")),
                ("first_name", models.CharField(max_length=200, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="images/avatars/default.png",
                        upload_to="images/avatars/%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=192, verbose_name="Инфа о себе")),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Дата рождения")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "ordering": ("user",),
            },
        ),
    ]
