# Generated by Django 5.0 on 2025-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_phone_number_alter_user_username_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=192, null=True, verbose_name="Инфа о себе"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="John", max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="Doe", max_length=255, verbose_name="Фамилия"),
        ),
    ]
