# Generated by Django 5.0 on 2025-08-18 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Unique Verification UUID"),
        ),
    ]
