# Generated by Django 5.0 on 2025-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_is_verified_user_verification_uuid"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False)),
                fields=("phone_number",),
                name="unique_non_empty_phone",
            ),
        ),
    ]
