# Generated by Django 5.0 on 2025-09-22 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_unique_non_empty_phone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_non_empty_phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+79999999999' or '89999999999'.",
                        regex="^((\\+7)|8)\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
